In [1]:
import numpy as np

In [2]:
#Dot Product
a = np.array([1, 2, 0])
b = np.array([1, 1, 1])
assert a.dot(b) == b.dot(a)
a.dot(b)
#Dot product multiplication -> scalar

def angle(a, b):
    maga = np.sqrt(a.dot(a))
    magb = np.sqrt(b.dot(b))
    costheta = a.dot(b) / maga
    costheta = costheta / magb
    return np.arccos(costheta)

In [3]:
angle(np.array([0, 1, 0]), np.array([0, 0, 1])) == np.pi / 2

True

In [4]:
np.random.seed(0)
a = np.random.rand(3, 2)
b = np.random.rand(2, 3)

assert a.dot(b).shape != b.dot(a).shape

In [5]:
#Dot product
a = np.array([1, 1, 1])
b = np.ones((3, 3))
a.dot(b), b.dot(a)

(array([3., 3., 3.]), array([3., 3., 3.]))

In [6]:
#Dot product
a = np.ones(4)
b = np.ones((3,3)) * 2
try:
    a.dot(b) 
except ValueError:
    print('ValueError ')

ValueError 


In [7]:
print(a.dot.__doc__)

a.dot(b, out=None)

    Dot product of two arrays.

    Refer to `numpy.dot` for full documentation.

    See Also
    --------
    numpy.dot : equivalent function

    Examples
    --------
    >>> a = np.eye(2)
    >>> b = np.ones((2, 2)) * 2
    >>> a.dot(b)
    array([[2.,  2.],
           [2.,  2.]])

    This array method can be conveniently chained:

    >>> a.dot(b).dot(b)
    array([[8.,  8.],
           [8.,  8.]])


In [8]:
a = np.eye(2)
a

array([[1., 0.],
       [0., 1.]])

In [9]:
b = np.ones((2, 2)) * 2
b

array([[2., 2.],
       [2., 2.]])

In [10]:
a.dot(b)

array([[2., 2.],
       [2., 2.]])

In [11]:
a.dot(b).dot(b)

array([[8., 8.],
       [8., 8.]])

In [12]:
print(np.matmul.__doc__)

matmul(x1, x2, /, out=None, *, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj, axes, axis])

Matrix product of two arrays.

Parameters
----------
x1, x2 : array_like
    Input arrays, scalars not allowed.
out : ndarray, optional
    A location into which the result is stored. If provided, it must have
    a shape that matches the signature `(n,k),(k,m)->(n,m)`. If not
    provided or None, a freshly-allocated array is returned.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

    .. versionadded:: 1.16
       Now handles ufunc kwargs

Returns
-------
y : ndarray
    The matrix product of the inputs.
    This is a scalar only when both x1, x2 are 1-d vectors.

Raises
------
ValueError
    If the last dimension of `x1` is not the same size as
    the second-to-last dimension of `x2`.

    If a scalar value is passed in.

See Also
--------
vdot : Complex-conjugating dot product.
tensordot : Sum products over arbitra

$P(A) = \frac{n(A)}{n(U)}$

In [13]:
def abtest(a, b):
    print(f'{a}\n\n{b}')
    try: 
        a @ b 
    except ValueError:
        print('a @ b Value Error')

    try:
        b @ a
    except ValueError:
        print('b @ a Value Error')

In [14]:
a = np.ones((2, 2)) * 3
b = np.ones((3)) * 2
abtest(a, b)

[[3. 3.]
 [3. 3.]]

[2. 2. 2.]
a @ b Value Error
b @ a Value Error


In [15]:
a = np.ones((3, 2, 1)) * np.pi
b = np.ones((7, 1)) * 2
abtest(a, b)

[[[3.14159265]
  [3.14159265]]

 [[3.14159265]
  [3.14159265]]

 [[3.14159265]
  [3.14159265]]]

[[2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]]
a @ b Value Error
b @ a Value Error


In [16]:
#Shapes
f = lambda a : print(f'{a}, {a.shape}\n')
f(np.ones(3))
f(np.ones((3, 1)))
f(np.ones((1, 3)))

[1. 1. 1.], (3,)

[[1.]
 [1.]
 [1.]], (3, 1)

[[1. 1. 1.]], (1, 3)



In [17]:
print('test ones: 3 x 1 @ 1 x 3 -> 3 x 3')
abtest(np.ones((3, 1)), np.ones((1, 3)))
print('test ones: 3 x 1 @ 3 x 1 -> Error')
abtest(np.ones((3, 1)), np.ones((3, 1)))
print('test ones: 1 x 3 @ 3 x 1 -> 1 x 1')
abtest(np.ones((1, 3)), np.ones((3, 1)))
print('test ones: 3 x 1 @ 3, -> error')
abtest(np.ones((3, 1)), np.ones(3))
print('test ones: 1 x 3 @ 3, -> 1')
abtest(np.ones((1, 3)), np.ones(3))
np.ones((1, 3)) @ np.ones(3)

test ones: 3 x 1 @ 1 x 3 -> 3 x 3
[[1.]
 [1.]
 [1.]]

[[1. 1. 1.]]
test ones: 3 x 1 @ 3 x 1 -> Error
[[1.]
 [1.]
 [1.]]

[[1.]
 [1.]
 [1.]]
a @ b Value Error
b @ a Value Error
test ones: 1 x 3 @ 3 x 1 -> 1 x 1
[[1. 1. 1.]]

[[1.]
 [1.]
 [1.]]
test ones: 3 x 1 @ 3, -> error
[[1.]
 [1.]
 [1.]]

[1. 1. 1.]
a @ b Value Error
test ones: 1 x 3 @ 3, -> 1
[[1. 1. 1.]]

[1. 1. 1.]
b @ a Value Error


array([3.])

In [51]:
def test_ascociativity():
    A = np.random.rand(3, 4, 7)
    B = np.random.rand(7, 4)
    C = np.random.rand(4, 11)
    
    #  3 x 2 x 11
    print(np.all(np.isclose(A @ B @ C, A @ (B @ C))))
test_ascociativity()

True


In [18]:
import jax.numpy as jnp
a = jnp.ones((3, 1))
b = jnp.ones((1, 3))
a @ b

DeviceArray([[1., 1., 1.],
             [1., 1., 1.],
             [1., 1., 1.]], dtype=float32)