In [1]:
import numpy as np
import jax
import timeit


In [4]:
a = list(range(10000))
b = []
%timeit for x in a: b.append(x + 5)

937 µs ± 3.51 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
%timeit b = [x + 5 for x in a]

389 µs ± 187 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
A = np.array(a)
%timeit B = A + 5

5.02 µs ± 5.21 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [8]:
"""Use the @ operator. @ is * for matrices"""

A = np.ones((2, 2))
B = np.ones((2, 2))
A @ B

array([[2., 2.],
       [2., 2.]])

In [11]:
"""The matrix multiplication @ is left ascociative"""
# a + b + c = (a + b) + c
# a / b / c = (a / b) / c
# a * b - c = (a * b) - c
#In math AZX = A(Zx)
#In Python AZX = (AZ)x

print(f'Right ascociative {2 * (3 - 4)}')
print(f'Left ascociative {(2 * 3) - 4}')
print(f'Python is left ascociative {2 * 3 - 4}')
print(-4 + 2 * 3)

Right ascociative -2
Left ascociative 2
Python is left ascociative 2
2


In [20]:
"""Let's say we want to multiply four matrices together"""
A = np.ones((2, 2)) * 2
B = np.ones((2, 3)) * 4
C = np.ones((3, 7)) * 2.2
D = np.ones((7, 1)) * 7

v1 = np.matmul(np.matmul(np.matmul(A, B), C), D)
v2 = A @ B @ C @ D
v1, v2

(array([[5174.4],
        [5174.4]]),
 array([[5174.4],
        [5174.4]]))

In [19]:
import jax.numpy as jnp
A = jnp.ones((2, 2)) * 2
B = jnp.ones((2, 3)) * 4
C = jnp.ones((3, 7)) * 2.2
D = jnp.ones((7, 1)) * 7
A @ B @ C @ D

DeviceArray([[5174.4004],
             [5174.4004]], dtype=float32)

In [25]:
A = jnp.ones((2, 2)) * 2
B = jnp.ones((2, 3)) * 4
C = jnp.ones((3, 7)) * 2.2
D = jnp.ones((7, 1)) * 7